package salesandinventory;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class frm_EPReports extends javax.swing.JFrame {
    dataForTableBuilding frisk = new dataForTableBuilding();
    SalesAndInventory sai = new SalesAndInventory();
    protected ResultSet asriel;
    /**
     * Creates new form frm_EPReports
     */
    public frm_EPReports() {
        initComponents();
        populateBothTables();
    }
    
    public void populateBothTables(){
        try { 
            sai.sql = "SELECT * FROM user_reg";
            sai.pStmt = sai.chainSmokersConnection().prepareStatement(sai.sql);
            asriel = sai.pStmt.executeQuery();
            this.employeeTable.setModel(frisk.tableModelMaker(asriel));
            sai.sql = "SELECT * FROM prod_reg";
            sai.pStmt = sai.chainSmokersConnection().prepareStatement(sai.sql);
            asriel = sai.pStmt.executeQuery();
            productTable.setModel(frisk.tableModelMaker(asriel));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frm_EPReports.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportPrintPrompt = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        dialogBtnCancel = new javax.swing.JButton();
        btnEmployeeTable = new javax.swing.JButton();
        btnProductTable = new javax.swing.JButton();
        dialogDetails = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaDetails = new javax.swing.JTextArea();
        btnExitDialog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnPreviewEmp = new javax.swing.JButton();
        btnPreviewPrd = new javax.swing.JButton();

        reportPrintPrompt.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Which table should be printed?");
        reportPrintPrompt.getContentPane().add(jLabel5);

        dialogBtnCancel.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        dialogBtnCancel.setText("Nothing.. Cancel this");
        dialogBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogBtnCancelActionPerformed(evt);
            }
        });
        reportPrintPrompt.getContentPane().add(dialogBtnCancel);

        btnEmployeeTable.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        btnEmployeeTable.setText("Employee Table");
        reportPrintPrompt.getContentPane().add(btnEmployeeTable);

        btnProductTable.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        btnProductTable.setText("Product Table");
        reportPrintPrompt.getContentPane().add(btnProductTable);

        textAreaDetails.setEditable(false);
        textAreaDetails.setColumns(20);
        textAreaDetails.setRows(5);
        textAreaDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(textAreaDetails);

        btnExitDialog.setText("Close");

        javax.swing.GroupLayout dialogDetailsLayout = new javax.swing.GroupLayout(dialogDetails.getContentPane());
        dialogDetails.getContentPane().setLayout(dialogDetailsLayout);
        dialogDetailsLayout.setHorizontalGroup(
            dialogDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExitDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        dialogDetailsLayout.setVerticalGroup(
            dialogDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetailsLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExitDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "isAdmin ", "Role", "Rate", "Address", "Age", "Contact Number", "Email", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Desc", "Manufacturer", "Supplier", "Quantity", "Price", "TotalPrice", "Discount", "DiscountedPrice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(productTable);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel1.setText("Reports on User and Product Tables");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employee Table");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Product Table");

        btnCancel.setBackground(new java.awt.Color(255, 204, 204));
        btnCancel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnCancel.setText("Exit");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(204, 255, 204));
        btnPrint.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnPreviewEmp.setBackground(new java.awt.Color(153, 255, 255));
        btnPreviewEmp.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnPreviewEmp.setText("Preview");
        btnPreviewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewEmpActionPerformed(evt);
            }
        });

        btnPreviewPrd.setBackground(new java.awt.Color(153, 255, 255));
        btnPreviewPrd.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnPreviewPrd.setText("Preview");
        btnPreviewPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewPrdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(546, 546, 546)
                .addComponent(jLabel3)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnPreviewEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPreviewPrd)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPreviewPrd)
                            .addComponent(btnPreviewEmp))
                        .addGap(42, 84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        setSize(new java.awt.Dimension(1199, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        frm_mainmenu openMe = new frm_mainmenu();
        openMe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        reportPrintPrompt.setAlwaysOnTop(true);
        reportPrintPrompt.setResizable(false);
        reportPrintPrompt.setLocationRelativeTo(null);
        reportPrintPrompt.setSize(908, 263);
        reportPrintPrompt.setVisible(true);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void dialogBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogBtnCancelActionPerformed
        // TODO add your handling code here:
        reportPrintPrompt.dispose();
    }//GEN-LAST:event_dialogBtnCancelActionPerformed

    private void btnPreviewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewEmpActionPerformed
        // TODO add your handling code here:
        //WORK ON THIS!!
        //finally decided to use a for loop in this..
        TableModel model = employeeTable.getModel();
        int rowYourBoat = employeeTable.getSelectedRow();
        int colMeMaybe = model.getColumnCount();
        String colHerByMe;
        Object[] values = new Object [ colMeMaybe ];
        for (int c = 0; c < colMeMaybe; c++){
            values[c] = model.getValueAt (rowYourBoat,c);
            colHerByMe = employeeTable.getModel().getColumnName(c);
            System.out.println(String.valueOf(values[c]));
            textAreaDetails.append(colHerByMe + " -- " +String.valueOf(values[c]) + "\n\n");
        }
        sai.fixThisFrameOrYourLife(355,481,false,true,this,dialogDetails);
    }//GEN-LAST:event_btnPreviewEmpActionPerformed

    private void btnPreviewPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewPrdActionPerformed
        // TODO add your handling code here:
        TableModel model = productTable.getModel();
        int rowYourBoat = productTable.getSelectedRow();
        int colMeMaybe = model.getColumnCount();
        String colHerByMe;
        Object[] values = new Object [ colMeMaybe ];
        for (int c = 0; c < colMeMaybe; c++){
            values[c] = model.getValueAt (rowYourBoat,c);
            colHerByMe = productTable.getModel().getColumnName(c);
            System.out.println(String.valueOf(values[c]));
            textAreaDetails.append(colHerByMe + " -- " +String.valueOf(values[c]) + "\n\n");
        }
        sai.fixThisFrameOrYourLife(355,481,false,true,this,dialogDetails);
    }//GEN-LAST:event_btnPreviewPrdActionPerformed
/*
    public void fixThisFrameOrYourLife(int A, int B, Boolean J, Boolean K, Component Q, JDialog R){
        //FIXTHISFRAMEORYOURLIFE
        //SETSIZE - INT-INT
        //SETRESIZABLE - BOOL
        //SETLOCATIONRELATIVETO - COMPONENT
        //SETVISIBLE - BOOL
        //JFRAME - JFRAMEGENERIC
        R.setSize(A, B);
        R.setResizable(J);
        R.setVisible(K);
        R.setLocationRelativeTo(Q);
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_EPReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_EPReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_EPReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_EPReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_EPReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEmployeeTable;
    private javax.swing.JButton btnExitDialog;
    private javax.swing.JButton btnPreviewEmp;
    private javax.swing.JButton btnPreviewPrd;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProductTable;
    private javax.swing.JButton dialogBtnCancel;
    private javax.swing.JDialog dialogDetails;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable productTable;
    private javax.swing.JDialog reportPrintPrompt;
    private javax.swing.JTextArea textAreaDetails;
    // End of variables declaration//GEN-END:variables
}
/*
class taskPopulateEmployee extends frm_EPReports{
    private void main() throws SQLException{
        try {
            sai.sql = "SELECT * FROM user_reg"; 
            sai.pStmt = sai.chainSmokersConnection().prepareStatement(sai.sql);
            asriel = sai.pStmt.executeQuery();
            this.employeeTable.setModel(frisk.tableModelMaker(asriel));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(taskPopulateEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

class taskPopulateProduct extends frm_EPReports{
    private void main() throws SQLException{
        try {
            sai.sql = "SELECT * FROM prod_reg";
            sai.pStmt = sai.chainSmokersConnection().prepareStatement(sai.sql);
            asriel = sai.pStmt.executeQuery();
            productTable.setModel(frisk.tableModelMaker(asriel));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(taskPopulateEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
*/