/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesandinventory;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author dell
 */
public class frm_ModifyPassword extends javax.swing.JFrame {
protected String SQL = "", OLDPASSWORD = "", NEWPASSWORD = "", USERNAME = "";
SalesAndInventory sai = new SalesAndInventory();
/**
     * Creates new form ModifyPassword
     */
    protected frm_ModifyPassword() {
        
        initComponents();
        setResizable(false);
        dataForModifyPassword mod = new dataForModifyPassword();
        txt_FromTheOtherSide.setText("Hello! " + mod.getUserName());
        txtGreeting.setText("<html><br>We are pleased to see you use our system :)<br>But for security purposes... <br>you need to change your password from the default one that was<br>provided by the system</html>");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ChangePassword = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_oldpass = new javax.swing.JPasswordField();
        txt_newpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtGreeting = new javax.swing.JLabel();
        txt_FromTheOtherSide = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_ChangePassword.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btn_ChangePassword.setText("Change Password");
        btn_ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ChangePassword);
        btn_ChangePassword.setBounds(50, 450, 370, 40);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Old Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 280, 370, 26);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 350, 370, 26);

        txt_oldpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_oldpass);
        txt_oldpass.setBounds(50, 310, 370, 40);

        txt_newpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_newpass);
        txt_newpass.setBounds(50, 380, 370, 40);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel3.setText("Modify Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 10, 300, 60);

        txtGreeting.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        txtGreeting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtGreeting.setText("Hello! ");
        txtGreeting.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(txtGreeting);
        txtGreeting.setBounds(50, 120, 370, 90);

        txt_FromTheOtherSide.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        txt_FromTheOtherSide.setText("FromTheOtherSide");
        getContentPane().add(txt_FromTheOtherSide);
        txt_FromTheOtherSide.setBounds(50, 80, 370, 40);
        getContentPane().add(txt_Username);
        txt_Username.setBounds(50, 240, 370, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 220, 370, 20);

        setSize(new java.awt.Dimension(501, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangePasswordActionPerformed
        // TODO add your handling code here:
        if (txt_oldpass.getText() == txt_newpass.getText()){ // verify that password isn't the same as!! true !!
            JOptionPane.showMessageDialog(null,"New password should be different from the old one.");
        }else{
            try {
                USERNAME = txt_Username.getText();
                NEWPASSWORD = txt_newpass.getText();
                sai.chainSmokersConnection();
                SQL = "UPDATE user_reg SET password = ?, isOld = ? WHERE employee_Id = ?";
                PreparedStatement pStmt;
                pStmt = sai.chainSmokersConnection().prepareStatement(SQL);
                
                pStmt.setString (1, NEWPASSWORD);
                pStmt.setBoolean (2, true);
                pStmt.setString (3, USERNAME);
                
                pStmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Successfully updated password of \nUSER " + USERNAME);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(frm_ModifyPassword.class.getName()).log(Level.SEVERE, null, ex);
            }
            frm_mainmenu openMainMenu = new frm_mainmenu();
            openMainMenu.setVisible(true);
            dispose();
            
        }
    }//GEN-LAST:event_btn_ChangePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ModifyPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ModifyPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ModifyPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ModifyPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ModifyPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChangePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtGreeting;
    private javax.swing.JLabel txt_FromTheOtherSide;
    private javax.swing.JTextField txt_Username;
    private javax.swing.JPasswordField txt_newpass;
    private javax.swing.JPasswordField txt_oldpass;
    // End of variables declaration//GEN-END:variables
}
