/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesandinventory;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author John
 */
public class frm_login extends javax.swing.JFrame{
    SalesAndInventory sai = new SalesAndInventory();
    String sql = "",user_txt = "", pass_txt = "", user_db = "", pass_db = "", userType="";
    String userUserEmployeeName = "", userRole = "", userAddress = "",userEmail ="",userGender = "";
    int userAge = 0, userContactNumber = 0;
    Boolean isAdministrator = null, isOld = null;
    
    /**
     * Creates new form frm_login
     */
    public frm_login() {
        initComponents();
        setResizable(false);
        System.out.println("@ frm_lgoin.java");
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setToolTipText("Input your username here.... ");
        getContentPane().add(txtUsername);
        txtUsername.setBounds(10, 80, 300, 40);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("authentication");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 0, 250, 52);

        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setToolTipText("Input your password here...");
        getContentPane().add(txtPassword);
        txtPassword.setBounds(10, 130, 300, 40);

        jPanel1.setLayout(new java.awt.GridLayout());

        btnLogin.setBackground(new java.awt.Color(204, 255, 204));
        btnLogin.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);

        btnExit.setBackground(new java.awt.Color(255, 204, 204));
        btnExit.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 210, 300, 70);

        setSize(new java.awt.Dimension(335, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        user_txt = txtUsername.getText();
        pass_txt = txtPassword.getText();
        //dont forget to modify this again.. just need to put the account details again.
        sql = "SELECT employee_Id, password, isAdmin, isOld, user_EmployeeName, user_Role, user_Address, user_Age, user_ContactNumber, user_Email, user_Gender FROM user_reg WHERE (employee_Id = '" + user_txt + "' AND password = '" + pass_txt + "')";
        try{
                Statement stmt = sai.chainSmokersConnection().createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                
                while(rs.next()){
                    user_db = rs.getString("employee_Id");
                    pass_db = rs.getString("password");
                    isAdministrator = rs.getBoolean("isAdmin");
                    isOld = rs.getBoolean("isOld");
                    userUserEmployeeName = rs.getString("user_EmployeeName");
                    userAddress = rs.getString("user_Address");
                    userRole = rs.getString("user_Role");
                    userAge = rs.getInt("user_Age");
                    userContactNumber = rs.getInt("user_ContactNumber");
                    userEmail = rs.getString("user_Email");
                    userGender = rs.getString("user_Gender");
                }
                //These statements just print out the status on the console.. of java.. (͡° ͜ʖ ͡°)
                System.out.println("ADMIN STATE @ AFTER While LOOP/REsultSet frm_login.java = " + isAdministrator); //delete this code when done
                if ((user_txt.equals(user_db)) && (pass_txt.equals(pass_db))){
                    System.out.println("ADMIN STATE @ DECISION IS USERADMIN ? = " + SalesAndInventory.isAdminPresent ); // should be null
                    
                    if (isAdministrator == true)//THis happens if ADMIN is using the system
                        userType = "ADM";
                    else//THis happens if EMPLOYEE is using the sytem
                        userType = "EMP";
                    SalesAndInventory.isAdminPresent = isAdministrator;//THIS SHOULD NOT BE NULL
                    System.out.println("ADMIN STATE @ AFTER IF/ELSE setting USERTYPE frm_login.java = " + isAdministrator); //delete this code when done
                    System.out.println("frm_login.java = " + SalesAndInventory.isAdminPresent + " " + userType );
                    JOptionPane.showMessageDialog(this, "Connected to DB as " + userType) ;
                    
                    dataForModifyPassword mod = new dataForModifyPassword();
                    dataForCurrentUser chara = new dataForCurrentUser();
                    
                    mod.setUserName(user_db);
                    mod.setPassword(pass_db);
                    mod.setUserType(userType);
                    
                    chara.setUserEmployeeName(userUserEmployeeName);
                    chara.setUserAddress(userAddress);
                    chara.setUserRole(userRole);
                    chara.setUserContactNumber(userContactNumber);
                    chara.setUserAge(userAge);
                    chara.setUserEmail(userEmail);
                    chara.setUserGender(userGender);
                    
                    //THIS IS FOR checking if the user has already modified his password...
                    if (isOld == true){
                        frm_mainmenu openMainMenu = new frm_mainmenu();
                        openMainMenu.setVisible(true);
                        dispose();
                    }else{
                        frm_ModifyPassword openForgetPassword = new frm_ModifyPassword();
                        openForgetPassword.setVisible(true);
                        dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Incorrect Credentials... \nMaybe you have entered a wrong USERNAME or Password...");
                }
                sai.chainSmokersConnection().close();
        }catch(SQLException | HeadlessException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
